# Programmation Orientée Objets

In [99]:
from functools import total_ordering
from operator import attrgetter
from datetime import date, timedelta
import numpy as np

In [7]:
# ville est un objet (data, instance) est de type str (classe str, modèle)
ville = "Toulouse"
# méthodes du stype str
print(ville.lower())
print(ville.startswith('To'))
# opérateurs au comportement spécifique
print(ville + " ville rose")
print(ville * 3)
print(ville[:3])
print('ou' in ville)
# built-ins fonctions au comportement spécifique
print(len(ville))
print(str(ville))
print(repr(ville))

toulouse
True
Toulouse ville rose
ToulouseToulouseToulouse
Tou
True
8
Toulouse
'Toulouse'


In [27]:
# d est un objet (une instance) de la classe date (type, modèle)
d = date.today()
# constructeur du type date
juin2 = date(2020,6,2)
print(d, juin2)
# attributs spécifiques du type date
print(d.year, d.month, d.day)
# méthodes spécifiques au type date
print(d.strftime('%d/%m/%Y'))
print(d.isoformat())
# opérateurs spécifiques du type date
print(d == date(2020,6,2))
print(d < date(2020,6,2))
print(d + timedelta(days=4))
# built-in fonctions
print(str(d))
print(repr(d))


2020-05-29 2020-06-02
2020 5 29
29/05/2020
2020-05-29
False
True
2020-06-02
2020-05-29
datetime.date(2020, 5, 29)


In [103]:
# définition du type Movie (classe) pour représenter des objets movies
@total_ordering
class Movie:
    def __init__(self, title, year, duration=None):
        """constructeur de la classe Movie"""
        self.title = title
        self.year = year
        self.duration = duration
        
    def age(self):
        return date.today().year - self.year
        
    # implémentation de built-in fonctions
    def __repr__(self):
        """redéfinition du comportement de repr/str"""
        return f'{self.title} ({self.year})'
    
    def __len__(self):
        return self.duration if self.duration is not None else 0
    
    # implémentation d'opérateurs
    def __eq__(self, other): # == et !=
        # optimisation
        if self is other:
            return True
        # if not isinstance(other, Movie):
        if type(other) != Movie:
            return NotImplemented
        return (self.title, self.year) == (other.title, other.year)
    
    def __lt__(self, other): # less than <
        if type(other) != Movie:
            return NotImplemented
        return (self.year, self.title) < (other.year, other.title)
        

In [104]:
movie1 = Movie("Joker", 2019, 122)
movie2 = Movie("Spider-Man: Far from Home", 2019, 129)
movie3 = Movie("Lord of War", 2005)
movies = [ movie1, movie2, movie3]
movies.append(Movie("The Lion King", 2019))
movies.append(Movie("The Lion King", 1994))
movies.append(Movie("The Man Who Knew Too Much", 1934))
movies.append(Movie("The Man Who Knew Too Much", 1956))
print(movie1.title, movie1.year, movie1.duration, sep=', ')
print(movie2.title, movie2.year, movie2.duration, sep=', ')
print(movie3.title, movie3.year, movie3.duration, sep=', ')
print(movie1) # appelle implicitement str
print(movie2)
movie1 # apelle implictement repr

Joker, 2019, 122
Spider-Man: Far from Home, 2019, 129
Lord of War, 2005, None
Joker (2019)
Spider-Man: Far from Home (2019)


Joker (2019)

In [105]:
movie1.age()

1

In [106]:
movies[-1].age()

64

In [107]:
[ m.age() for m in movies ]

[1, 1, 15, 1, 26, 86, 64]

In [93]:
print(movie1 < movie2)
print(movie1 > movie2)
print(movie1 <= movie2)
print(movie1 >= movie2)

True
False
True
False


In [88]:
# tri avec l'opérateur <
sorted(movies)

[The Man Who Knew Too Much (1934),
 The Man Who Knew Too Much (1956),
 The Lion King (1994),
 Lord of War (2005),
 Joker (2019),
 Spider-Man: Far from Home (2019),
 The Lion King (2019)]

In [100]:
# sorted(movies, key=lambda m: m.title)
sorted(movies, key=attrgetter('title'))

[Joker (2019),
 Lord of War (2005),
 Spider-Man: Far from Home (2019),
 The Lion King (2019),
 The Lion King (1994),
 The Man Who Knew Too Much (1934),
 The Man Who Knew Too Much (1956)]

In [101]:
# sorted(movies, key=lambda m: (m.title,m.year))
sorted(movies, key=attrgetter('title','year'))

[Joker (2019),
 Lord of War (2005),
 Spider-Man: Far from Home (2019),
 The Lion King (1994),
 The Lion King (2019),
 The Man Who Knew Too Much (1934),
 The Man Who Knew Too Much (1956)]

In [94]:
print(movie1 == movie2, movie1 is movie2)
print(movie1 == movie1, movie1 is movie1)
m = Movie("Joker", 2019, 122)
print(movie1 == m, movie1 is m)
print(movie1 != m, movie1 is not m)
print(movie1 == 55)
print(55 == movie1)
print(m in movies)

False False
True True
True False
False True
False
False
True


In [78]:
carre = np.zeros((3,3), dtype=int)
carre

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [79]:
carre == 0

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [80]:
0 == carre

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [102]:
carre.diagonal()

array([0, 0, 0])

In [37]:
type(movie1)

__main__.Movie

In [63]:
movies

[Joker (2019), Spider-Man: Far from Home (2019), Lord of War (2005)]

In [64]:
len(movie1)

122

In [48]:
for m in movies:
    print(m.title)

Joker
Spider-Man: Far from Home
Lord of War


In [49]:
[ m.title for m in movies ]

['Joker', 'Spider-Man: Far from Home', 'Lord of War']

In [51]:
", ".join(m.title for m in movies if m.year==2019)

'Joker, Spider-Man: Far from Home'

In [53]:
min(m.year for m in movies)

2005

In [56]:
dureeTotale = sum(m.duration for m in movies if m.duration is not None)
dureeTotale

251

In [57]:
movie3.duration = 122

In [58]:
dureeTotale = sum(m.duration for m in movies if m.duration is not None)
dureeTotale

373

In [60]:
movies[2].duration

122

In [109]:
# Héritage
class Media:
    pass

class Movie(Media):
    pass

class TvSeries(Media):
    pass